version: '3'
services:
  influxdb:
    image: influxdb:1.3.5
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=testdatadb
  grafana:
    build: ./grafana
    ports:
      - "3000:3000"
    volumes:
      - "./grafana/dashboards/:/var/lib/grafana/dashboards"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_DASHBOARDS_JSON_ENABLED=true
  testrunner:
    build: ./testrunner
    tty: true
